### ISSUE TITLE
[Question] - Initial full page background with relative scroll

### ISSUE THREAD

**Issue by mtompkins** [BGStock/jquery-background-video#3]
Thanks for fielding the question in advance. It's a helpful bit of a plugin.

What I'm trying to accomplish is, load the initial video fullscreen (and responsive), but allow it to scroll with a "relative" function. Very much like a one-page responsive site with an initial full video background landing. Here is an example: https://family.olegnax.com/forest/index.html I purchased this to get an idea of a possible approach to the JS. Unfortunately the resizing has some issue when a browser is dragged larger.

Using your sample CSS as a reference, I thought that as your `jquery-background-video-wrapper` is set to `position:relative` that it would (hopefully) scroll but I'm guessing the js call using `background: true` causes an override?

If you please advise? Many thanks.

**Comment by GusRuss89** [comment]
Hi @mtompkins, what behaviour are you actually seeing? The video in the link that you posted behaves exactly how the plugin should by default. If you're seeing some parallax or fixed (no scrolling) behaviour, then maybe it's coming from some CSS in a theme or template that you're using?

**Comment by mtompkins** [comment]
Thanks again for taking the time to respond @GusRuss89 I'll strip away a new gulp-webapp (I use yeoman) and create something to cleanly inspect and we can look at together. Of course I believe I've already stripped everything away, but thought a quick inquiry might shed some light. Will revert.

**Comment by GusRuss89** [comment]
@mtompkins are you using the fullScreen setting? If so, try setting that to false and instead make the video wrapper using your own CSS. E.g. `.jquery-background-video-wrapper { height: 100vh; }`

**Comment by mtompkins** [comment]
I was using the fullScreen setting. Will do and confirm.

**Comment by mtompkins** [comment]
That was it - thanks for the handholding and sharing you work.
Rgrds.
