### ISSUE TITLE
GET /undefined/ if not set "poster" attr

### ISSUE THREAD

**Issue by higimo** [BGStock/jquery-background-video#4]
`<video class="my-background-video jquery-background-video" loop autoplay muted>`

generated GET request to site.net/undefined and crash this script.

**Comment by GusRuss89** [comment]
Hi @higimo I made a commit that should fix this. 

https://github.com/BGStock/jquery-background-video/commit/1a9e66bd5378f69e0d2d0c6b18f60ba33ed99a6f

Please update and let me know if that doesn't work for you. If it does, please close the issue.

**Comment by higimo** [comment]
Good news! Thx.
